[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
headless = false
runOnSave = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
showErrorDetails = true
