"""Initial migration

Revision ID: 4a71a61f0f97
Revises: 06ea8b2d6864
Create Date: 2025-07-15 15:31:22.363181

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a71a61f0f97"
down_revision: Union[str, None] = "06ea8b2d6864"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
